### ISSUE TITLE
Should we .gitignore package-lock.json?

### ISSUE THREAD

**Issue by MattyAyOh** [assembleapp/slim#1]
After I installed the packages, the lock file was created and source control marked it as a new file--

Should we add this file to the .gitignore?  Should I delete it?  

With Cocoa there is a package manager called CocoaPods, and they recommended adding the lock file to the git ignore, but just wanted to check

**Comment by graysonwright** [comment]
Oh, I was going to add a note about this.

In JS land right now, there are two competing package installers `npm` and `yarn`.
They both do pretty much the same thing, but for some reason I've heard `yarn` does a better job.

We've got a `yarn.lock` file committed right now: https://github.com/assembleapp/slim/blob/master/yarn.lock

We should standardize on which package manager to use, and then commit the respective lock file.

**Comment by graysonwright** [comment]
If you want to give yarn a shot, try `yarn install`, then `yarn start`.
You might need to `brew install yarn` if it's not already on your system.

Here's some motivation for `yarn` over `npm`:

* https://www.sitepoint.com/yarn-vs-npm/
* [Yarn GitHub star count](https://github.com/yarnpkg/yarn): 31785
* [NPM GitHub star count](https://github.com/npm/npm): 16515

And a migration guide for yarn.
https://yarnpkg.com/lang/en/docs/migrating-from-npm/

If we want to go the yarn route, I can update the README to replace `npm` commands with the relevant `yarn` commands.

**Comment by MattyAyOh** [comment]
gotcha, I just picked npm because that was the first one recommended by the React install sites

idgaf, just let me know which one you want to pick, i don't foresee any issue either way as the underlying packages are the same anyways, right?

**Comment by graysonwright** [comment]
> the underlying packages are the same anyways, right?

Yup. Let's go with Yarn, it's my default and it's great. 😄

**Comment by MattyAyOh** [comment]
it's literally the same exact thing as npm but yeah it's easy to use
