### ISSUE TITLE
Generic server

### ISSUE THREAD

**Issue by graysonwright** [assembleapp/slim#15]
No way around it. We need to set up a generic server that can handle requests from frontend app.

We can create a new repo for it at `assembleapp/engine`.
We can use this issue to track its initial features, then switch over to that repo's issue tracker once it's able to stand on its own.

We can use the server to distinguish between the "development" and "production" environments. In "production", the server is configured to connect directly to Accupac's databases. In "development", the server connects to local databases filled with test data.

We should start by hard-coding the behavior for dev mode, just so this doesn't block the frontend development too heavily. After that, we can start to gradually build up the server's functionality.

**Comment by graysonwright** [comment]
Useful links for the server:

* [Sinatra](http://sinatrarb.com/) for a super-bare-bones API
* [Run a predefined script in a Docker container, from Ruby](https://github.com/assembleapp/assemble/blob/master/app/models/block_run.rb#L14-L57)
* [Deploy the server to our own private cloud](https://deis.com/workflow/) (see #16)

**Comment by graysonwright** [comment]
Scrapping all of this, copy/pasted code from https://github.com/mattyayoh/nimbuspos.

```bash
$ curl -X POST http://localhost:3000/evaluate -H "Content-Type: application/json" -d '{ "code": "2 + 2" }'
4⏎
```

**Comment by graysonwright** [comment]
```bash
$ brew install postgresql
$ brew services start postgresql
```

**Comment by MattyAyOh** [comment]
dirty copy-paster

**Comment by graysonwright** [comment]
¯\_(ツ)_/¯

**Comment by MattyAyOh** [comment]
\ \
you dropped this

**Comment by graysonwright** [comment]
Fine, ya stickler.
`¯\_(ツ)_/¯`

**Comment by MattyAyOh** [comment]
![](http://i.imgur.com/FSGvo.gif)
